feat: workfing version of add-fence-client which adds WebAPI as a Fence client

diff --git a/helm/ohdsi-webapi/templates/ohdsi-webapi-client-create-job.yaml b/helm/ohdsi-webapi/templates/ohdsi-webapi-client-create-job.yaml
--- a/helm/ohdsi-webapi/templates/ohdsi-webapi-client-create-job.yaml
+++ b/helm/ohdsi-webapi/templates/ohdsi-webapi-client-create-job.yaml
@@ -10,11 +10,11 @@ spec:
         app: gen3job
     spec:
       restartPolicy: OnFailure
-      serviceAccountName: webapi-secrets
+      serviceAccountName: {{ .Values.webapiSecretsServiceAccountName }}
       volumes:
         - name: config-volume
           secret:
-            secretName: "fence-config"
+            secretName: "fence-config" # TODO does not seem to be used anywhere....instead "fence-dbcreds" is used...
         - name: shared-volume
           emptyDir: {}
       initContainers:
@@ -22,9 +22,9 @@ spec:
           image: curlimages/curl:latest
           imagePullPolicy: IfNotPresent
           command: ["/bin/sh","-c"]
-          args: ["while [ $(curl -sw '%{http_code}' http://fence-service -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for fence...'; done"]
+          args: ["while [ $(curl -sw '%{http_code}' {{ .Values.fenceUrl }} -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for fence...'; done"]
       containers:
-        - name: fence-client
+        - name: add-fence-client
           image: "quay.io/cdis/fence:master"
           imagePullPolicy: {{ .Values.image.pullPolicy }}
           command: ["/bin/bash"]
@@ -33,8 +33,9 @@ spec:
             - |
               client_exists() {
                 local client_name="$1"
-                local existing=$(fence-create client-list | grep "\"client_id\": \"${client_name}\"")
-                if [[ -n "$existing" ]](); then
+                echo -e "\n\n>>========== CHECKING if Fence client already exists for $client_name... ============\n\n"
+                local existing=$(fence-create client-list | grep "['\"]name['\"]: ['\"]${client_name}['\"]")
+                if [[ -n "$existing" ]]; then
                   return 0  # client exists
                 fi
                 return 1
@@ -46,15 +47,15 @@ spec:
                 client_name="atlas"
 
                 if client_exists $client_name; then
-                  echo "found existing OIDC client for $atlas_hostname... deleting so it can be recreated..."
+                  echo -e "\n\n>>========== FOUND existing OIDC client for $atlas_hostname... deleting so it can be recreated... ============\n\n"
                   fence-create client-delete --client $client_name
                 fi
 
-                echo "creating fence oidc client for $atlas_hostname"
-                local secrets=$(fence-create client-create --client $client_name --urls https://${atlas_hostname}/WebAPI/user/oauth/callback?client_name=OidcClient --username atlas --allowed-scopes openid profile email user | tail -1)
+                echo -e "\n\n>>========== CREATING NEW Fence oidc client for $atlas_hostname ... ============\n\n"
+                local secrets=$(fence-create client-create --client $client_name --urls https://${atlas_hostname}/WebAPI/user/oauth/callback?client_name=OidcClient --username atlas --allowed-scopes openid user | tail -1)
                 # secrets looks like ('CLIENT_ID', 'CLIENT_SECRET')
                 if [[ ! $secrets =~ (\'(.*)\', \'(.*)\') ]]; then
-                  echo "Failed generating oidc client for $client_name"
+                  echo -e "\n\n>>========== FAILED generating oidc client for $client_name  ============\n\n"
                   return 1
                 fi
                 local FENCE_CLIENT_ID="${BASH_REMATCH[2]}"
@@ -69,11 +70,11 @@ spec:
               new_client
               rc=$?
 
-              if [[ $rc -ne 0 ]](); then
-                echo "Error: new_client failed with exit code $rc"
+              if [[ $rc -ne 0 ]]; then
+                echo -e "\n\n>>========== ERROR: new_client failed with exit code $rc  ============\n\n"
                 exit $rc
               else
-                echo "Success: new_client ran successfully"
+                echo -e "\n\n>>========== SUCCESS: new_client ran successfully  ============\n\n"
                 exit 0
               fi
           env:
@@ -101,8 +102,14 @@ spec:
                   name: fence-dbcreds
                   key: database
                   optional: false
+            - name: PGPORT
+              valueFrom:
+                secretKeyRef:
+                  name: fence-dbcreds
+                  key: port
+                  optional: true                
             - name: DB
-              value: postgresql://$(PGUSER):$(PGPASSWORD)@$(PGHOST):5432/$(PGDB)
+              value: postgresql://$(PGUSER):$(PGPASSWORD)@$(PGHOST)$(PGPORT)/$(PGDB)
             - name: PYTHONPATH
               value: /var/www/fence
             - name: FENCE_PUBLIC_CONFIG
@@ -118,7 +125,7 @@ spec:
               readOnly: true
               mountPath: "/var/www/fence/fence-config.yaml"
               subPath: fence-config.yaml
-        - name: kubectl
+        - name: update-webapi-config
           image: bitnami/kubectl:latest
           volumeMounts:
             - name: "shared-volume"
@@ -137,8 +144,8 @@ spec:
               FENCE_CLIENT_ID=$(cat /shared/client_id | base64)
               FENCE_CLIENT_SECRET=$(cat /shared/client_secret | base64)
               echo "waiting for ohdsi-webapi-config secret to appear"
-              until kubectl get secret ohdsi-webapi-config >/dev/null 2>&1
-              do
+              until kubectl get secret ohdsi-webapi-config; do
+                echo "---- get secret Command failed -- status $?"
                 echo "..."
                 sleep 5
               done
