setting up usersync job for helm.

diff --git a/helm/fence/templates/usersync-cron.yaml b/helm/fence/templates/usersync-cron.yaml
--- a/helm/fence/templates/usersync-cron.yaml
+++ b/helm/fence/templates/usersync-cron.yaml
@@ -4,9 +4,9 @@
 # gen3 job run usersync
 #
 # Optional Arguments:
-#     ADD_DBGAP Force attempting a dbgap sync if "true", falls back to manifest configuration
+#     ADD_DBGAP Force attempting a dbgap sync if "true", falls back on user.yaml
 #               by defualt. i.e. this isn't required for a dbGaP sync to happen
-#               default: "false" - fall back to manifest configuration
+#               default: "false" - fall back on user.yaml
 #               ex: gen3 job run usersync ADD_DBGAP true
 #
 #     ONLY_DBGAP Forces ONLY a dbgap sync if "true", IGNORING user.yaml
@@ -18,6 +18,7 @@ kind: Job
 metadata:
   name: usersync
 spec:
+  # schedule: "*/30 * * * *"  # Runs every 30 minutes
   # Kill the job if it has not finished within 4 hours
   activeDeadlineSeconds: 14400
   backoffLimit: 0
@@ -54,11 +55,14 @@ spec:
         - name: fence-sshconfig
           configMap:
             name: "fence-sshconfig"
-      initContainers:
-        - name: wait-for-fence
-          image: curlimages/curl:latest
-          command: ["/bin/sh","-c"]
-          args: ["while [ $(curl -sw '%{http_code}' http://fence-service -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for fence...'; done"]
+        - name: cred-volume
+          secret:
+            secretName: aws-config-fence
+      # initContainers:
+      #   - name: wait-for-fence
+      #     image: curlimages/curl:latest
+      #     command: ["/bin/sh","-c"]
+      #     args: ["while [ $(curl -sw '%{http_code}' http://fence-service -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for fence...'; done"]
       containers:
       - name: usersync
         image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
@@ -66,8 +70,8 @@ spec:
         env:
           {{- toYaml .Values.env | nindent 12 }}
         volumeMounts:
-          - name: user-yaml
-            mountPath: /mnt/shared/user.yaml
+          - name: shared-data
+            mountPath: /mnt/shared
           - name: "config-volume"
             readOnly: true
             mountPath: "/var/www/fence/fence-config.yaml"
@@ -87,8 +91,6 @@ spec:
             readOnly: true
             mountPath: "/var/www/fence/fence_google_storage_creds_secret.json"
             subPath: fence_google_storage_creds_secret.json
-          - name: shared-data
-            mountPath: /mnt/shared
           - name: "fence-sshconfig"
             mountPath: "/root/.ssh/config"
             subPath: "config"
@@ -98,9 +100,9 @@ spec:
           # Script always succeeds if it runs (echo exits with 0)
           - |
             echo 'options use-vc' >> /etc/resolv.conf
-            sleep 1000
             pip3 install SQLAlchemy==1.3.6
-            if [[ "$SYNC_FROM_DBGAP" != True && "$ADD_DBGAP" != "true" ]]; then
+            # can be removed once this is merged: https://github.com/uc-cdis/fence/pull/1096
+            if [[ "$SYNC_FROM_DBGAP" != "true" && "$ADD_DBGAP" != "true" ]]; then
               if [[ -f /mnt/shared/user.yaml ]]; then
                 echo "running fence-create"
                 time fence-create sync --arborist http://arborist-service --yaml /mnt/shared/user.yaml
@@ -122,7 +124,7 @@ spec:
               echo "$output"
               # Echo what files we are seeing on dbgap ftp to Slack
               # We only do this step every 12 hours and not on weekends to reduce noise
-              if [[ -n "$SLACK_SEND_DBGAP" && "$SLACK_SEND_DBGAP" = True ]]; then
+              if [[ -n "$SLACK_SEND_DBGAP" && "$SLACK_SEND_DBGAP" = "true" ]]; then
                 files=$(grep "Reading file" "$output")
                 let hour=$(date -u +10#%H)
                 let dow=$(date -u +10#%u)
@@ -159,9 +161,12 @@ spec:
                 key: useryaml_s3path
         volumeMounts:
           - name: user-yaml
-            mountPath: /mnt/shared/user.yaml
+            mountPath: /var/www/fence
           - name: shared-data
             mountPath: /mnt/shared
+          - name: cred-volume
+            mountPath: "/home/ubuntu/.aws/credentials"
+            subPath: credentials
         command: ["/bin/bash" ]
         args:
           - "-c"
@@ -170,6 +175,26 @@ spec:
             source "${GEN3_HOME}/gen3/lib/utils.sh"
             gen3_load "gen3/gen3setup"
 
+            if [ "${userYamlS3Path}" = 'none' ]; then
+              echo "using local user.yaml"
+              cp /var/www/fence/user.yaml /mnt/shared/user.yaml
+            else
+              # -----------------
+              echo "awshelper downloading ${userYamlS3Path} to /mnt/shared/user.yaml"
+              n=0
+              until [ $n -ge 5 ]; do
+                echo "Download attempt $n"
+                aws s3 cp "${userYamlS3Path}" /mnt/shared/user.yaml && break
+                n=$[$n+1]
+                sleep 2
+                echo "test 1"
+              done
+            fi
+            if [[ ! -f /mnt/shared/user.yaml ]]; then
+              echo "awshelper failed to retrieve /mnt/shared/user.yaml"
+              exit 1
+            fi
+            #-----------
             echo "awshelper updating etl configmap"
             if ! gen3 gitops etl-convert < /mnt/shared/user.yaml > /tmp/user.yaml; then
               echo "ERROR: failed to generate ETL config"
@@ -177,6 +202,9 @@ spec:
             fi
             kubectl delete configmap fence > /dev/null 2>&1
             kubectl create configmap fence --from-file=/tmp/user.yaml
+            if [ "${slackWebHook}" != 'None' ]; then
+              curl -X POST --data-urlencode "payload={\"text\": \"AWSHelper: Syncing users on ${gen3Env}\"}" "${slackWebHook}"
+            fi
             echo "Helper exit ok"
       restartPolicy: Never
 {{- end }}
